---
- name: update
  apt:
    update_cache: yes
    force_apt_get: yes

# base utils
- name: downloaders
  apt:
    name:
      - curl
      - wget
      - aria2
      - netcat
      - pv
    state: present
- name: file utils
  apt:
    name:
      - mc
      - fdupes
      - tree
      - rename
      - gddrescue
    state: present
- name: compression
  apt:
    name:
      - lzop
      - pigz
      - unrar
      - cabextract
      - upx-ucl
    state: present
- name: mail utils
  apt:
    name:
      - swaks
    state: present
- name: monitoring
  apt:
    name:
      - htop
      - nmon
      - tmux
    state: present
- name: remote file systems
  apt:
    name:
      - curlftpfs
      - sshfs
      - nfs-common
      - samba
      - cifs-utils
      - krb5-user
    state: present
- name: network tools
  apt:
    name:
      - nmap
    state: present
- name: cli helpers
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - { src: "bin/addtohosts", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/check_zombie_procs", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/cht.sh", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/cpucheck", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/deskinfo", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/dfm", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/disklife", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/dm", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/dnscheck", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/ds", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/filehasher.py", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/gencsr-ec.sh", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/gencsr.sh", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/genself.sh", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/getcpufreqs", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/getcpugov", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/gotopup", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/hostfilereset.sh", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/instcert.sh", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/ipv6range", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/listports", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/nmnt", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/nscan", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/numnt", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/randgen", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/randmac", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/randpass", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/renamer.py", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/setcpugov", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/smbmnt", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/smbumnt", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/smnt", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/sumnt", dest: "{{ home }}/bin/", mode: "0755" }
    - { src: "bin/uptimecalc.py", dest: "{{ home }}/bin/", mode: "0755" }
