---
- name: git
  apt:
    name:
      - git
    state: present
- name: hugoup
  template:
    src: "bin/hugoup"
    dest: "{{ home }}/bin/hugoup"
- name: hugoup chown
  file:
    path: "{{ home }}/bin/hugoup"
    owner: "{{ user }}"
    group: "{{ user }}"
    chmod: "0755"
- name: hugoup install
  command: "{{ home }}/bin/hugoup"
