---
- hosts: all
  become: yes
  tasks:
    - name: add syncthing key
      apt_key:
        url: https://syncthing.net/release-key.txt
        state: present
    - name: add repository
      apt_repository:
        validate_certs: no
        repo: deb [arch=amd64] https://apt.syncthing.net/ syncthing stable
        state: present
        filename: syncthing
        update_cache: yes
    - name: syncthing
      apt:
        name:
        - syncthing
        state: present
    #- name: nextcloud desktop client
      #flatpak:
        #name: org.nextcloud.Nextcloud
        #state: present
        #remote: gnome
