---
- hosts: all
  become: yes
  tasks:
    - name: 20_js
      blockinfile:
        path: "{{lookup('env', 'HOME')}}/.config/cfg/20_js.cfg"
        create: yes
        marker: "# {mark} Javascript ENV"
        block: |
          export NPM_PACKAGES="${HOME}/.npm-packages"
          PATH="${NPM_PACKAGES}/bin:${PATH}"
          export MANPATH="$NPM_PACKAGES/share/man:${MANPATH}"
    - name: 20_js ownership
      file:
        path: "{{lookup('env', 'HOME')}}/.config/cfg/20_js.cfg"
        group: "{{lookup('env', 'USER')}}"
        owner: "{{lookup('env', 'USER')}}"
    - name: npmrc remove
      file:
        path: "{{lookup('env', 'HOME')}}/.npmrc"
        state: absent
    - name: npmrc
      blockinfile:
        path: "{{lookup('env', 'HOME')}}/.npmrc"
        create: yes
        marker: ""
        block: |
          prefix=${HOME}/.local/npm-packages
    - name: npmrc ownership
      file:
        path: "{{lookup('env', 'HOME')}}/.npmrc"
        group: "{{lookup('env', 'USER')}}"
        owner: "{{lookup('env', 'USER')}}"

