---
- hosts: all
  become: yes
  tasks:
    - name: remove snap-store
      snap:
        - snap-store
        state: absent
    - name:
    - name: gnome software store
      apt:
        name:
        - gnome-software
        - flatpak
        - gnome-software-plugin-flatpak
        - gnome-software-plugin-snap
        state: present
    - name: flatpak repo
      shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - name: application helpers
      apt:
        name:
        - apt-transport-https
        - pkg-config
        - git
        - upx-ucl
        state: present
    - name: downloaders
      apt:
        name:
        - curl
        - wget
        - aria2
        state: present
    - name: file utils
      apt:
        name:
        - mc
        - fdupes
        - tree
        - gddrescue
        - rename
        state: present
    - name: editor
      apt:
        name:
        - vim
        state: present
    - name: compression
      apt:
        name:
        - lzop
        - pigz
        - unrar
        - cabextract
        state: present
    - name: benchmarking
      apt:
        name:
        - fio
        - siege
        state: present
    - name: mail utils
      apt:
        name:
        - swaks
        state: present
    - name: remote file systems
      apt:
        name:
        - curlftpfs
        - sshfs
        - nfs-common
        - samba
        - cifs-utils
        - krb5-user
        state: present
    - name: monitoring
      apt:
        name:
        - htop
        - nmon
        - tmux
        state: present
