---
- hosts: all
  become: yes
  tasks:
    - name: hosts remove notfound
      replace:
        path: /etc/nsswitch.conf
        regexp: '\s+\[NOTFOUND=return\]'
        replace: ''
    - name: hosts remove unvavail
      replace:
        path: /etc/nsswitch.conf
        regexp: '\s+\[!UNAVAIL=return\]'
        replace: ''
    - name: remove winbind
      replace:
        path: /etc/nsswitch.conf
        regexp: '\s+winbind'
        replace: ''
    - name: passwd winbind
      replace:
        backup: yes
        path: /etc/nsswitch.conf
        regexp: '^(passwd.*)$'
        replace: '\1 winbind'
    - name: group winbind
      replace:
        backup: yes
        path: /etc/nsswitch.conf
        regexp: '^(group.*)$'
        replace: '\1 winbind'

