---
- hosts: all
  become: yes
  tasks:
    - name: application helpers
      apt:
        name:
        - apt-transport-https
        - pkg-config
        - git
        - upx-ucl
        state: latest
    # snap store removal
    - name: remove snap-store
      snap:
        name: snap-store
        state: absent
    - name: gnome software store
      apt:
        name:
        - gnome-software
        - flatpak
        - gnome-software-plugin-flatpak
        - gnome-software-plugin-snap
        state: present
    # flatpak flathub repo
    - name: flatpak repo
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
