---
- hosts: all
  become: yes
  tasks:
    - name: application helpers
      apt:
        name:
        - apt-transport-https
        - pkg-config
        - git
        - upx-ucl
        state: latest
    - name: bin
      git:
        repo: "https://github.com/ppreeper/bin"
        dest: "{{lookup('env', 'HOME')}}/bin"
        update: yes
      become: yes
      become_user: "{{lookup('env', 'USER')}}"
    - name: go install
      command: "{{lookup('env', 'HOME')}}/bin/goup"
    - name: chmod mnt
      file:
        path: '/mnt'
        mode: '0777'
    - name: add bin dir
      file:
        path: "{{lookup('env', 'HOME')}}/bin"
        state: directory
        group: "{{lookup('env', 'USER')}}"
        owner: "{{lookup('env', 'USER')}}"
    - name: add app dir
      file:
        path: "{{lookup('env', 'HOME')}}/app"
        state: directory
        group: "{{lookup('env', 'USER')}}"
        owner: "{{lookup('env', 'USER')}}"
    - name: add mnt dir
      file:
        path: "{{lookup('env', 'HOME')}}/mnt"
        state: directory
        group: "{{lookup('env', 'USER')}}"
        owner: "{{lookup('env', 'USER')}}"
    - name: add .cfg dir
      file:
        path: "{{lookup('env', 'HOME')}}/.config/cfg"
        state: directory
        group: "{{lookup('env', 'USER')}}"
        owner: "{{lookup('env', 'USER')}}"
    - name: add .cfg load
      blockinfile:
        path: "{{lookup('env', 'HOME')}}/.zshrc"
        create: yes
        marker: "# {mark} cfg loader"
        block: |
          for f in ${HOME}/.config/cfg/*cfg
          do
            source ${f}
          done
    - name: zshrc ownership
      file:
        path: "{{lookup('env', 'HOME')}}/.zshrc"
        group: "{{lookup('env', 'USER')}}"
        owner: "{{lookup('env', 'USER')}}"
    - name: remove snap-store
      snap:
        - snap-store
        state: absent
    - name:
    - name: gnome software store
      apt:
        name:
        - gnome-software
        - flatpak
        - gnome-software-plugin-flatpak
        - gnome-software-plugin-snap
        state: present
    - name: flatpak repo
      shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - name: downloaders
      apt:
        name:
        - curl
        - wget
        - aria2
        state: present
    - name: file utils
      apt:
        name:
        - mc
        - fdupes
        - tree
        - gddrescue
        - rename
        state: present
    - name: editor
      apt:
        name:
        - vim
        state: present
    - name: compression
      apt:
        name:
        - lzop
        - pigz
        - unrar
        - cabextract
        state: present
    - name: benchmarking
      apt:
        name:
        - fio
        - siege
        state: present
    - name: mail utils
      apt:
        name:
        - swaks
        state: present
    - name: remote file systems
      apt:
        name:
        - curlftpfs
        - sshfs
        - nfs-common
        - samba
        - cifs-utils
        - krb5-user
        state: present
    - name: network tools
      apt:
        name:
        - nmap
        - nmapsi4
        state: present
    - name: monitoring
      apt:
        name:
        - htop
        - nmon
        - tmux
        state: present
    - name: minicom config clear
      file:
        path: "{{lookup('env', 'HOME')}}/.minirc.dfl"
        state: absent
    - name: minicom config
      blockinfile:
        path: "{{lookup('env', 'HOME')}}/.minirc.dfl"
        create: yes
        marker: ""
        block: |
          pu port             /dev/ttyUSB0
          pu baudrate         38400
          pu bits             8
          pu parity           N
          pu stopbits         1
          pu rtscts           No
    - name: minicom config set ownership
      file:
        path: "{{lookup('env', 'HOME')}}/.minirc.dfl"
        group: "{{lookup('env', 'USER')}}"
        owner: "{{lookup('env', 'USER')}}"
    - name: minicom
      apt:
        name:
        - minicom
        state: present
    - name: add existing user "{{lookup('env','USER')}}" to tty,dialout
      user:
        name: "{{ lookup('env','USER') }}"
        groups: tty,dialout
        append: yes
