---
- hosts: all
  become: yes
  tasks:
    - name: vim and git
      apt:
        name:
        - vim
        - git
        state: latest
    - name: nerdcommenter
      git:
        repo: "https://github.com/preservim/nerdcommenter"
        dest: "{{lookup('env', 'HOME')}}/.vim/pack/vendor/start/nerdcommenter"
        update: yes
      become: yes
      become_user: "{{lookup('env', 'USER')}}"
    - name: nerdtree
      git:
        repo: "https://github.com/preservim/nerdtree.git"
        dest: "{{lookup('env', 'HOME')}}/.vim/pack/vendor/start/nerdtree"
        update: yes
      become: yes
      become_user: "{{lookup('env', 'USER')}}"
    - name: auto-pairs
      git:
        repo: "https://github.com/jiangmiao/auto-pairs.git"
        dest: "{{lookup('env', 'HOME')}}/.vim/pack/plugins/start/auto-pairs"
        update: yes
      become: yes
      become_user: "{{lookup('env', 'USER')}}"
    - name: fugitive
      git:
        repo: "https://tpope.io/vim/fugitive.git"
        dest: "{{lookup('env', 'HOME')}}/.vim/pack/plugins/start/fugitive"
        update: yes
      become: yes
      become_user: "{{lookup('env', 'USER')}}"
    - name: jedi-vim
      git:
        repo: "https://github.com/davidhalter/jedi-vim.git"
        dest: "{{lookup('env', 'HOME')}}/.vim/pack/plugins/start/jedi-vim"
        update: yes
      become: yes
      become_user: "{{lookup('env', 'USER')}}"
    - name: lightline
      git:
        repo: "https://github.com/itchyny/lightline.vim"
        dest: "{{lookup('env', 'HOME')}}/.vim/pack/plugins/start/lightline.vim"
        update: yes
      become: yes
      become_user: "{{lookup('env', 'USER')}}"
    - name: syntastic
      git:
        repo: "https://github.com/vim-syntastic/syntastic"
        dest: "{{lookup('env', 'HOME')}}/.vim/pack/plugins/start/syntastic"
        update: yes
      become: yes
      become_user: "{{lookup('env', 'USER')}}"
    - name: ultisnips
      git:
        repo: "https://github.com/SirVer/ultisnips"
        dest: "{{lookup('env', 'HOME')}}/.vim/pack/plugins/start/ultisnips"
        update: yes
      become: yes
      become_user: "{{lookup('env', 'USER')}}"
    - name: vim-gitgutter
      git:
        repo: "https://github.com/airblade/vim-gitgutter"
        dest: "{{lookup('env', 'HOME')}}/.vim/pack/plugins/start/vim-gitgutter"
        update: yes
      become: yes
      become_user: "{{lookup('env', 'USER')}}"
    - name: vim-go
      git:
        repo: "https://github.com/fatih/vim-go.git"
        dest: "{{lookup('env', 'HOME')}}/.vim/pack/plugins/start/vim-go"
        update: yes
      become: yes
      become_user: "{{lookup('env', 'USER')}}"
