---
- hosts: all
  become: yes
  tasks:
    - name: evolution groupware client
      apt:
        name:
        - evolution
        - evolution-ews
        - evolution-indicator
        - evolution-plugin-bogofilter
        - evolution-plugin-pstimport
        - evolution-plugin-spamassassin
        - evolution-plugins
        state: present
    - name: add libreoffice repository
      apt_repository:
        validate_certs: no
        repo: ppa:libreoffice/ppa
        update_cache: yes
    - name: libreoffice
      apt:
        name:
        - libreoffice
        state: present
