---
- hosts: all
  become: yes
  tasks:
    - name: ruby
      apt:
        name:
        - ruby
        state: latest
    - name: 20_ruby
      blockinfile:
        path: "{{lookup('env', 'HOME')}}/.config/cfg/20_ruby.cfg"
        create: yes
        marker: "# {mark} Ruby ENV"
        block: |
          PATH=$(gem env gempath | awk -F":" '{print $1"/bin"}'):$PATH
    - name: config set ownership
      file:
        path: "{{lookup('env', 'HOME')}}/.config/cfg/20_ruby.cfg"
        group: "{{lookup('env', 'USER')}}"
        owner: "{{lookup('env', 'USER')}}"

