---
- hosts: all
  become: yes
  tasks:
    - name: mariadb client
      apt:
        name:
        - mariadb-client
        state: present
    - name: add key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present
    - name: remove postgres repository
      file:
        path: /etc/apt/sources.list.d/postgres.list
        state: absent
    - name: add postgres repository
      apt_repository:
        validate_certs: no
        repo: deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename|lower }}-pgdg main
        state: present
        filename: postgres
        update_cache: yes
    - name: postgresql-12 client
      apt:
        name:
        - postgresql-client-12
        - postgresql-server-dev-12
        state: present
    - name: sqlite3
      apt:
        name:
        - sqlite3
        state: present
    - name: tds mssql
      apt:
        name:
        - freetds-bin
        - freetds-dev
        - tdsodbc
        - unixodbc
        - unixodbc-dev
        state: present
