---
- hosts: all
  become: yes
  tasks:
    - name: tds mssql
      apt:
        name:
        - freetds-bin
        - freetds-dev
        - tdsodbc
        - unixodbc
        - unixodbc-dev
        state: present
