---
- hosts: all
  become: yes
  tasks:
    - name: add wireguard repository
      apt_repository:
        validate_certs: no
        repo: ppa:wireguard/wireguard
        update_cache: yes
    - name: gnome network vpn connectors
      apt:
        name:
        - network-manager-openconnect-gnome
        - network-manager-openvpn-gnome
        - network-manager-pptp-gnome
        - network-manager-ssh-gnome
        - network-manager-vpnc-gnome
        - wireguard
        state: latest
