---
- hosts: all
  become: yes
  tasks:
    - name: remmina
      apt:
        name:
        - remmina
        - remmina-plugin-rdp
        - remmina-plugin-vnc
        - remmina-plugin-nx
        - remmina-plugin-spice
        - remmina-plugin-secret
        state: present
