---
- hosts: all
  become: yes
  tasks:
    - name: image tools (system)
      apt:
        name:
        - jpegoptim
        - pngquant
        - gifsicle
        state: latest
    - name: image tools (npm)
      npm:
        name: svgo
        global: yes
        state: latest
    - name: av codecs and tools
      apt:
        name:
        - ffmpeg
        - gstreamer1.0-libav
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-plugins-ugly
        - oggz-tools
        - ogmtools
        - opus-tools
        - vorbis-tools
        - flac
        - mkvtoolnix
        - vpx-tools
        - cuetools
        - shntool
        - sox
        - libavcodec-extra
        - libdvdread7
        - dvdbackup
        - vobcopy
        - mediainfo
        - ubuntu-restricted-extras
        - ubuntu-restricted-addons
        state: present
    - name: media-player
      apt:
        name:
        - gnome-mpv
        state: present
