---
- hosts: all
  become: yes 
  tasks:
    - name: evolution groupware client
      apt:
        name:
        - evolution
        - evolution-ews
        - evolution-indicator
        - evolution-plugin-bogofilter
        - evolution-plugin-pstimport
        - evolution-plugin-spamassassin
        - evolution-plugins
        state: present
