---
- hosts: all
  become: yes
  tasks:
    - name: yay cleanup
      file:
        state: absent
        path: "{{lookup('env', 'HOME')}}/hugo"
    - name: hugo git
      git:
        repo: "https://github.com/gohugoio/hugo.git"
        dest: "{{lookup('env', 'HOME')}}/hugo"
        update: yes
        version: v0.70.0
      become: yes
      become_user: "{{lookup('env', 'USER')}}"
    - name: hugo install
      command: go install --tags extended
      become: yes
      become_user: "{{lookup('env', 'USER')}}"
      args:
        chdir: "{{lookup('env', 'HOME')}}/hugo"
