---
- name: postgresql repo key
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present
- name: postgres repository stat
  stat:
    path: "/etc/apt/sources.list.d/postgres.list"
  register: stat_result
- name: postgres repository remove
  file:
    path: "/etc/apt/sources.list.d/postgres.list"
    state: absent
  when: stat_result.stat.exists
- name: postgres repository add
  apt_repository:
    validate_certs: no
    repo: "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename|lower }}-pgdg main"
    state: present
    filename: postgres
    update_cache: yes
