---
- name: update
  apt:
    update_cache: yes
    force_apt_get: yes

# language support
# go
# requirement
- name: git
  apt:
    name: 
      - git
    state: present
# goup installer
- name: goup
  template:
    src: "bin/goup"
    dest: "{{ home }}/bin/goup"
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"
# cfg go
- name: cfg 20_go
  template:
    src: "cfg/20_go.cfg"
    dest: "{{ config }}/cfg/20_go.cfg"
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"
# install go
- name: install go
  command: "{{ home }}/bin/goup"
# install gopls
- name: install gopls
  become: '{{ user }}'
  environment:
    - GO111MODULE: "on"
  shell: "go get golang.org/x/tools/gopls@latest"
